import pandas as pd 
df= pd.read_csv("C:\\Users\\kiran\\DIML\\Python\\examples\\pandas\\Employee.csv")
print(df)
print('============')
print(df.head())
print('============')
print(df.info())
print('============')
print(df.describe())
print('============')
print(df.head(10))
print('============')
print(df.tail(5))
print('============')
print(df.head(-1)) 
print('============')
print(df['FIRST_NAME'])
print('============')
f1=df[df['SALARY'] > 10000]
print(f1)
print('============')